@startuml
title Espace Administration - Modération & Système
left to right direction
skinparam actorStyle awesome

actor "Administrateur" as A

rectangle "Organisation & Administration" {
    usecase "Valider / Refuser une organisation" as ValOrg
    usecase "Voir historique demandes organisation" as HistOrg
    usecase "Valider / Refuser demande recruteur" as ValRec
    usecase "Gérer les utilisateurs" as Users
    usecase "Attribuer le rôle administrateur" as RoleA
}

A --> ValOrg
A --> HistOrg
A --> ValRec
A --> Users
A --> RoleA

HistOrg ..> ValOrg : <<extend>>
@enduml